Docs: Removed redundant files and moved Readme.md
iai-group/UserSimCRS pull request #118
Opened 2023-03-02 15:12 UTC by adityakode

fixes #116 
Removed Redundand files `docs/config.md` and `docs/User_modeling.md`.
Moved  `docs/source/README.md` under `docs`.

2023-03-03 16:06 UTC, NoB0 requested changes
Please update the section `User modeling` in the file `docs/source/component.rst` with the content from `docs/User_modeling.md`. 
Guidelines for `.rst` are available [here](https://github.com/iai-group/guidelines/blob/main/restructuredtext/README.md).

2023-03-03 17:40 UTC, adityakode commented
in `docs/source`  , file [user_modeling.rst](https://github.com/iai-group/UserSimCRS/blob/main/docs/source/user_modeling.rst) is present . Should I delete that too ?
And in `docs/source/component.rst` do I overwrite the user modelling section with content from `docs/User_modeling.md` or should I append it ?

2023-03-03 18:22 UTC, adityakode commented
hi @NoB0  I have made the changes.
PS review. 
Can you tell me ps why tests are failing ? so that I can make amends

2023-03-07 06:59 UTC, NoB0 approved these changes
LGTM. I made some suggestions to avoid redundancy.

2023-03-07 06:59 UTC, NoB0 commented on docs/source/components.rst
>  User modeling consists of three sub-components: preference model, context model, and persona. The responsibility of the preference model is to capture users’ individual tastes and thus allow for a pe
```suggestion
User modeling consists of three sub-components: preference model, context model, and persona.
```

2023-03-07 06:59 UTC, NoB0 commented on docs/source/components.rst
> +Persona contains user variables, e.g., cooperativeness.
```suggestion
Persona is used to capture user-specific traits, e.g., cooperativeness.
```

2023-03-07 07:00 UTC, NoB0 commented
The tests are failing because we are doing some breaking changes. For this PR you do not have to worry about the tests.

2023-03-13 14:17 UTC, NoB0 commented
@adityakode could you please solve the conflicts with the main branch so I can merge the changes.

2023-05-31 14:23 UTC, NoB0 commented
Closing this PR as the merge conflicts are resolved in PR #143

2023-05-31 14:23 UTC, closed without merging