Improvement/#34 argparse and config file for simulation
iai-group/UserSimCRS pull request #71
Opened 2022-08-23 10:39 UTC by JAfzali

2023-01-03 12:32 UTC, NoB0 commented
- Introduce a default config file to run the simulation
- Load and update configuration with command line arguments
- Save simulation configuration in `data/runs` 
- Load intent classifier supported by DialogueKit (i.e., cosine and Rasa DIET)
- Add abstract methods in `SampleAgent` to run `run_simulation.py`
- Create #88 as follow up to mypy issue

2023-01-10 19:52 UTC, kbalog commented
@NoB0 Is this ready to be reviewed or are you still working on it?

2023-01-11 10:55 UTC, NoB0 commented
It can be reviewed.

2023-01-13 22:52 UTC, kbalog requested changes
Wondering if `get_intent_classifier()`, `load_cosine_classifier()`, and `load_rasa_diet_classifier()` could be moved to DialogueKit instead?  Or at least the latter two? They could receive specific arguments (intent schema, annotated dialogues file, etc.) instead of a config file.

2023-01-16 10:35 UTC, NoB0 commented on config/default/config_default.yaml
> +ontology: data/domains/movies.yaml
Done.

2023-01-16 10:35 UTC, NoB0 commented on config/default/config_default.yaml
> +rasa_dialogues: data/agents/moviebot/annotated_dialogues_rasa_agent.yml
Done.

2023-01-16 10:35 UTC, NoB0 commented on usersimcrs/run_simulation.py
> +    domain = Domain(config["ontology"].get())
Done.

2023-01-16 10:36 UTC, NoB0 commented on usersimcrs/run_simulation.py
> +    config = confuse.Configuration("usrsimcrs")
Fixed.

2023-01-16 10:36 UTC, NoB0 commented on usersimcrs/run_simulation.py
> +    config.set_file(DEFAULT_CONFIG_PATH.format("general"))
Removed.

2023-01-16 10:36 UTC, NoB0 commented on usersimcrs/run_simulation.py
> +    config.set_file(DEFAULT_CONFIG_PATH.format(agent_id))
Removed.

2023-01-16 10:36 UTC, NoB0 commented on usersimcrs/run_simulation.py
> +    with open(f"data/runs/{output_name}.meta.yaml", "w") as f:
Done.

2023-01-16 10:45 UTC, NoB0 commented
`get_intent_classifier` is specific to this repository and should not be moved in my opinion. 
I suppose the methods `load_cosine_classifier` and `load_rasa_diet_classifier` could be "utils" function in DK.

2023-01-16 17:20 UTC, NoB0 commented
> LGTM
> 
> Can you add a P2 issue for moving `load_cosine_classifier` and `load_rasa_diet_classifier` as util functions to DK? (and link the issue as a todo as comments to these methods)

Issue #92

2023-01-16 17:21 UTC, merged